# Generated by Django 4.1 on 2022-09-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnwordseasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='for_test',
            field=models.IntegerField(default=0),
        ),
    ]
